# Generated by Django 5.2.4 on 2026-04-24 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_favorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Избранный проект', 'verbose_name_plural': 'Избранные проекты'},
        ),
    ]
